<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\Core\Domain.Orders\Current.Core.Domain.Orders\Current.Core.Domain.Orders.csproj" />
    <ProjectReference Include="..\..\Core\SharedKernel\Current.Core.SharedKernel\Current.Core.SharedKernel.csproj" />
    <ProjectReference Include="..\..\Application\Current.Application\Current.Application.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
