<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.21" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\Domain.Orders\Current.Core.Domain.Orders\Current.Core.Domain.Orders.csproj" />
    <ProjectReference Include="..\..\Core\SharedKernel\Current.Core.SharedKernel\Current.Core.SharedKernel.csproj" />
    <ProjectReference Include="..\..\Application\Current.Application\Current.Application.csproj" />
    <ProjectReference Include="..\..\Infrastructure\Current.Infrastructure\Current.Infrastructure.csproj" />
  </ItemGroup>

</Project>
